<?php
namespace BackOffice\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\Http\Exception\NotFoundException;
use Cake\ORM\Locator\LocatorAwareTrait;
use Cake\Routing\Router;
use Cake\Utility\Hash;
use Cake\Utility\Inflector;

/**
 * Class CrudController
 *
 * @package BackOffice\Controller
 */
class CrudController extends AppController
{

	use LocatorAwareTrait;

	/**
	 * @var \Cake\ORM\Table
	 */
	private $model;

	/**
	 * @var array
	 */
	private $activeMenu;

	/**
	 * @var array
	 */
	private $parentMenu;

	/**
	 * @return array
	 */
	public function implementedEvents() {
		return array_merge(parent::implementedEvents(), [
			'View.beforeRender' => 'beforeViewRender'
		]);
	}

	/**
	 * @inheritDoc
	 * @param \Cake\Event\Event $event
	 *
	 * @return \Cake\Http\Response|null
	 */
	public function beforeFilter( Event $event ) {

		// Load parent active menu
		$this->activeMenu = $this->BackOffice->getActiveMenu() ?: [];
		if (!$this->activeMenu) {
			throw new NotFoundException(__('ActiveMenu not found'));
		}

		// Load model
		$this->modelClass = $this->getRequest()->getParam('modelClass');
		$this->model = $this->loadModel($this->modelClass);

		// Continue
		return parent::beforeFilter($event);
	}

	/**
	 * Before render
	 *
	 * @param \Cake\Event\Event $event
	 *
	 * @return \Cake\Http\Response|null
	 */
	public function beforeRender( Event $event ) {
		$this->set([
			'activeMenu' => $this->activeMenu,
			'modelClass' => $this->modelClass,
			'entity' => $this->model->getAlias()
		]);
		return parent::beforeRender( $event ); // TODO: Change the autogenerated stub
	}

	/**
	 * Before view render
	 *
	 * @param \Cake\Event\Event $event
	 */
	public function beforeViewRender(Event $event)
	{
		/** @var \BackOffice\View\AppView $appView */
		$appView = $event->getSubject();

		// Set breadcrumb
		if ($this->activeMenu) {
			$appView->Page->addCrumb( $this->activeMenu['title'], $this->activeMenu['action'] );
		}
		$appView->Page->addCrumb( Inflector::pluralize($this->model->getAlias()), [ 'action' => 'index', 'modelClass' => $this->modelClass ] );

		// Add create action
		if ($appView->view === 'index') {
			$appView->Page->addAction('secondary', [ 'title' => 'New ' .  Inflector::singularize($this->model->getAlias()), 'icon' => 'add_circle_outline', 'action' => [ 'action' => 'create', 'modelClass' => $this->modelClass ] ]);
		}

	}

	public function index()
	{

	}

	public function create()
	{
		$this->set('_schema', $this->model->getSchema());
	}

}
