<?php

namespace BackOffice\Lib\Twig;

use Twig\Cache\FilesystemCache;

/**
 * Class BackOfficeCache
 *
 * @package BackOffice\Lib\Twig
 */
class BackOfficeCache extends FilesystemCache
{

	/**
	 * @param string $key
	 */
	public function load( $key )
	{
		// TODO: purge cache
		parent::load( $key );
	}

	/**
	 * @param string $name
	 * @param string $className
	 *
	 * @return string
	 */
	public function generateKey( $name, $className )
	{
		// TODO: purge cache
		return parent::generateKey( $name, $className ); // TODO: Change the autogenerated stub
	}

}
