<?php
namespace BackOffice\View\Helper;

use Cake\View\Helper\FormHelper as BaseFormHelper;

/**
 * Form helper
 */
class FormHelper extends BaseFormHelper
{
	/**
	 * Initialize
	 *
	 * @param array $config
	 */
	public function initialize( array $config ) {
		parent::initialize( $config );
		$this->setConfig([
			'errorClass' => 'is-invalid',
			'templates' => [
				'error' => '<div class="invalid-feedback">{{content}}</div>',
				'formGroup' => '{{label}}{{input}}',
				'nestingLabel' => '{{hidden}}{{input}}<label{{attrs}}>{{text}}</label>',
				'inputContainer' => '<div class="{{class}} {{type}}{{required}}">{{content}}{{info}}</div>',
				'inputContainerError' => '<div class="{{class}} {{type}}{{required}}">{{content}}{{error}}</div>'
			]
		]);
	}

	/**
	 * @inheritDoc
	 */
	protected function _getInput( $fieldName, $options ) {
		// Set default values
		$options += [
			'class' => '',
			'labelOptions' => []
		];

		// Determine input class
		switch (strtolower($options['type'])) {
			case 'radio':
			case 'checkbox':
				$options['labelOptions'] = [ 'class' => 'custom-control-label' ];
				$options['class'] = 'custom-control-input ' . $options['class'];
				break;
			default:
				$options['class'] = 'form-control ' . $options['class'];
		}

		// Return parent call
		return parent::_getInput( $fieldName, $options );
	}

	/**
	 * @inheritDoc
	 */
	protected function _getLabel( $fieldName, $options ) {
		// Set default values
		$options += [
			'label' => null
		];

		// Determine input class
		switch (strtolower($options['type'])) {
			case 'radio':
			case 'checkbox':
				$options['label'] = [ 'text' => $options['label'], 'class' => 'custom-control-label' ];
				break;
		}

		return parent::_getLabel( $fieldName, $options ); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	protected function _inputContainerTemplate( $options ) {
		// Determine container class
		switch (strtolower($options['options']['type'])) {
			case 'radio':
				$options['options']['templateVars'] = [ 'class' => 'custom-control custom-radio' ];
				break;
			case 'checkbox':
				$options['options']['templateVars'] = [ 'class' => 'custom-control custom-checkbox' ];
				break;
		}

		return parent::_inputContainerTemplate( $options ); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function control( $fieldName, array $options = [] ) {
		$options += [
			'templateVars' => []
		];

		// Input container options
		if (isset($options['container'])) {
			$options['templateVars'] = array_merge($options['templateVars'], $options['container']);
			unset($options['container']);
		}

		// Input info options
		if (isset($options['info'])) {
			$options['templateVars'] = array_merge($options['templateVars'], [ 'info' => $this->Html->tag('small', $options['info'], [ 'id' => $fieldName . '_help', 'class' => 'form-text text-muted' ]) ]);
			unset($options['info']);
		}

		// Render control
		return parent::control( $fieldName, $options );
	}

}
